# Generated by Django 4.2.6 on 2024-02-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_alter_post_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('graduation', 'Graduation'), ('dinner', 'Dinner')], max_length=15),
        ),
    ]
