# Generated by Django 5.0.3 on 2024-03-27 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0013_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
