# Generated by Django 4.1.2 on 2023-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
