# Generated by Django 4.2.6 on 2024-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('graduation', 'Graduation'), ('dinner', 'Dinner')], max_length=15),
        ),
    ]
