# Generated by Django 4.2.6 on 2024-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='left',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='right',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
