# Generated by Django 4.2.6 on 2024-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_back_collection_left_collection_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
