# Generated by Django 4.2.6 on 2024-04-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='price',
        ),
    ]
