# Generated by Django 4.2.6 on 2024-02-24 20:59

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('collection', '0007_alter_collection_material_alter_collection_price'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='collection',
#             name='price',
#         ),
#     ]
