# Generated by Django 5.0.3 on 2024-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
